version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
        - echo Starting Build Stage
        - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - 'dist/**/*'

cache:
  paths:
    - '/root/.npm/**/*'
    - '/node_modules/'